### ISSUE TITLE
[Question] what these parameters mean?

### ISSUE THREAD

**Issue by unanchoi** [qfgaohao/pytorch-ssd#174]
Hi.
I have question about input parameters
1. What is difference between --base_net and --pretrained_ssd
2. What is difference between --freeze_base_net and --freeze_ner
3. what does mean the parameter 'debug_step'  in training

https://github.com/qfgaohao/pytorch-ssd/blob/f61ab424d09bf3d4bb3925693579ac0a92541b0d/train_ssd.py#L41-L67

**Comment by SarBH** [comment]
This is a guess:
`--base_net` its the ability to provide a pretrained base  (the classifier backbone part (vgg16, mobilenetV1, etc) 
`--pretrained_ssd`  providing a pretrained complete SSD model (base and SSD portions)
If you look in the readme there are some urls of models, some of them have "ssd", and i guess you should pass them with `--pretrained_ssd` others dont have "ssd" so you would need to pass via `--base_net`
And depending on wether u want to train the SSD portions (except the head because that's num_classes specific) you choose what to freeze

**Comment by unanchoi** [comment]
thank you for comment!
